name: mrbgem test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install package
      run: sudo apt install libonig-dev
    - name: download mruby
      run: git clone --depth 1 -b "2.0.1" "https://github.com/mruby/mruby.git" mruby
    - name: run test
      run: cd mruby && MRUBY_CONFIG="../.travis_config.rb" ./minirake all test
